2022-05-20 17:24:57,443 - can't compare datetime.datetime to datetime.date
Traceback (most recent call last):
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\connect_sql.py", line 132, in <module>
    print(data2 > dado)
TypeError: can't compare datetime.datetime to datetime.date
