2022-07-26 17:26:50,817 - descriptor 'strftime' for 'datetime.date' objects doesn't apply to a 'str' object
Traceback (most recent call last):
  File "C:/Users/allan.mesquita/OneDrive - NTT/Documents/Projetos/Automacao_Evidencias/Script/Test_Zone/main_qualidade2.py", line 125, in <module>
    resultado = validacao.rec_validation(aba, qtd_linhas)
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\Test_Zone\Modulos\validacao.py", line 297, in rec_validation
    print(save.connect())
  File "C:\Users\allan.mesquita\OneDrive - NTT\Documents\Projetos\Automacao_Evidencias\Script\Test_Zone\Modulos\class_erros.py", line 193, in connect
    data_evidencia = datetime.strftime(self.aba[f'H{self.linha}'].value, '%d/%m/%Y')  # dado vazio
TypeError: descriptor 'strftime' for 'datetime.date' objects doesn't apply to a 'str' object
